@startuml

title __SERVICE's Class Diagram__\n

  namespace com.deta.kopmart_backend {
    namespace service {
      interface com.deta.kopmart_backend.service.CartService {
          {abstract} + checkout()
          {abstract} + delete()
          {abstract} + getCart()
          {abstract} + mergeLocalCart()
      }
    }
  }
  

  namespace com.deta.kopmart_backend {
    namespace service {
      interface com.deta.kopmart_backend.service.CategoryService {
          {abstract} + findAll()
          {abstract} + findByCategoryType()
          {abstract} + findByCategoryTypeIn()
          {abstract} + save()
      }
    }
  }
  

  namespace com.deta.kopmart_backend {
    namespace service {
      interface com.deta.kopmart_backend.service.OrderService {
          {abstract} + cancel()
          {abstract} + findAll()
          {abstract} + findByBuyerEmail()
          {abstract} + findByBuyerPhone()
          {abstract} + findByStatus()
          {abstract} + findOne()
          {abstract} + finish()
      }
    }
  }
  

  namespace com.deta.kopmart_backend {
    namespace service {
      interface com.deta.kopmart_backend.service.ProductInOrderService {
          {abstract} + findOne()
          {abstract} + update()
      }
    }
  }
  

  namespace com.deta.kopmart_backend {
    namespace service {
      interface com.deta.kopmart_backend.service.ProductService {
          {abstract} + decreaseStock()
          {abstract} + delete()
          {abstract} + findAll()
          {abstract} + findAllByNameLike()
          {abstract} + findAllInCategory()
          {abstract} + findFourNewestProducts()
          {abstract} + findOne()
          {abstract} + increaseStock()
          {abstract} + offSale()
          {abstract} + onSale()
          {abstract} + save()
          {abstract} + update()
      }
    }
  }
  

  namespace com.deta.kopmart_backend {
    namespace service {
      interface com.deta.kopmart_backend.service.UserService {
          {abstract} + findByRole()
          {abstract} + findOne()
          {abstract} + save()
          {abstract} + update()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
