@startuml

title __REPOSITORY's Class Diagram__\n

  namespace com.deta.kopmart_backend {
    namespace repository {
      interface com.deta.kopmart_backend.repository.CartRepository {
      }
    }
  }
  

  namespace com.deta.kopmart_backend {
    namespace repository {
      interface com.deta.kopmart_backend.repository.OrderRepository {
          {abstract} + findAllByBuyerEmailOrderByOrderStatusAscCreateTimeDesc()
          {abstract} + findAllByBuyerPhoneOrderByOrderStatusAscCreateTimeDesc()
          {abstract} + findAllByOrderByOrderStatusAscCreateTimeDesc()
          {abstract} + findAllByOrderStatusOrderByCreateTimeDesc()
          {abstract} + findByOrderId()
      }
    }
  }
  

  namespace com.deta.kopmart_backend {
    namespace repository {
      interface com.deta.kopmart_backend.repository.ProductCategoryRepository {
          {abstract} + findAllByOrderByCategoryType()
          {abstract} + findByCategoryType()
          {abstract} + findByCategoryTypeInOrderByCategoryTypeAsc()
      }
    }
  }
  

  namespace com.deta.kopmart_backend {
    namespace repository {
      interface com.deta.kopmart_backend.repository.ProductInOrderRepository {
      }
    }
  }
  

  namespace com.deta.kopmart_backend {
    namespace repository {
      interface com.deta.kopmart_backend.repository.ProductInfoRepository {
          {abstract} + findAllByCategoryTypeOrderByProductIdAsc()
          {abstract} + findAllByOrderByProductId()
          {abstract} + findAllByProductNameContainingIgnoreCase()
          {abstract} + findAllByProductStatusOrderByProductIdAsc()
          {abstract} + findByProductId()
          {abstract} + findTop4ByOrderByProductIdDesc()
      }
    }
  }
  

  namespace com.deta.kopmart_backend {
    namespace repository {
      interface com.deta.kopmart_backend.repository.UserRepository {
          {abstract} + findAllByRole()
          {abstract} + findByEmail()
      }
    }
  }
  

  namespace com.deta.kopmart_backend {
    namespace repository {
      interface com.deta.kopmart_backend.repository.WishlistRepository {
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
