spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: org.postgresql.Driver
    username: grbmxgdwyhnohn
    password: d86897ee5000aaf571eb030102e15909da3a7a2a06618ee7da6076baa6490a69
    url: jdbc:postgresql://ec2-34-198-186-145.compute-1.amazonaws.com:5432/d52ucp2itbdsj5
    platform: postgres
    initialization-mode: always
    continue-on-error: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database: postgresql
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  queries:
    users-query: select email, password, active from users where email=?
    roles-query: select email, role from users where email=?
server:
  servlet:
    context-path: /api
jwtSecret: deta.gantenk
jwtExpiration: 86400