spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: asdf
    url: jdbc:postgresql://localhost:5432/kopmart
    platform: postgres
    initialization-mode: always
    continue-on-error: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database: postgresql
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  queries:
    users-query: select email, password, active from users where email=?
    roles-query: select email, role from users where email=?
server:
  servlet:
    context-path: /api
jwtSecret: deta.gantenk
jwtExpiration: 86400